name: lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.3.1

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint
